services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: crm_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_this_password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - /var/backups/crm:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crm_user -d crm_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - crm_network

  # Redis for messaging and caching
  redis:
    image: redis:7-alpine
    container_name: crm_redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-change_this_redis_password}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-change_this_redis_password}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - crm_network

  # User Service
  user_service:
    build:
      context: ./services/user_service
      dockerfile: Dockerfile
    container_name: crm_user_service
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql+asyncpg://crm_user:${POSTGRES_PASSWORD}@postgres:5432/crm_db
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - ENVIRONMENT=production
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 2
    networks:
      - crm_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Budget Service
  budget_service:
    build:
      context: ./services/budget_service
      dockerfile: Dockerfile
    container_name: crm_budget_service
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql+asyncpg://crm_user:${POSTGRES_PASSWORD}@postgres:5432/crm_db
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - ENVIRONMENT=production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002 --workers 2
    networks:
      - crm_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend (React/Vite with Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: crm_frontend
    restart: unless-stopped
    depends_on:
      user_service:
        condition: service_healthy
      budget_service:
        condition: service_healthy
    networks:
      - crm_network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: crm_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - /var/log/crm:/var/log/nginx
    depends_on:
      - frontend
      - user_service
      - budget_service
    networks:
      - crm_network

volumes:
  postgres_data:
  redis_data:

networks:
  crm_network:
    driver: bridge
