"""Add freight_value_total field to budgets

Revision ID: 011_add_freight_value_total
Revises: 010_add_freight_type_to_budgets
Create Date: 2024-12-23 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011_add_freight_value_total'
down_revision = '010_add_freight_type_to_budgets'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('freight_value_total', sa.Float(), nullable=True, comment='Valor total do frete'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'freight_value_total')
    # ### end Alembic commands ###