"""Initial migration for budget_service

Revision ID: 001
Revises: 
Create Date: 2024-10-24 15:10:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_email', sa.String(length=255), nullable=True),
    sa.Column('client_phone', sa.String(length=50), nullable=True),
    sa.Column('client_company', sa.String(length=255), nullable=True),
    sa.Column('client_cnpj', sa.String(length=20), nullable=True),
    sa.Column('client_address', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('total_commission', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_sale_with_icms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ipi_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ipi_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('freight_type', sa.String(length=10), nullable=True),
    sa.Column('freight_value_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('weight_difference_display', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_id'), 'budgets', ['id'], unique=False)
    op.create_table('budget_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('commission_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('commission_percentage_actual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('commission_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('icms_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('icms_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sale_price_with_icms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ipi_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ipi_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('delivery_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_items_id'), 'budget_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budget_items_id'), table_name='budget_items')
    op.drop_table('budget_items')
    op.drop_index(op.f('ix_budgets_id'), table_name='budgets')
    op.drop_table('budgets')
    # ### end Alembic commands ###